# Generated by Django 5.0.1 on 2024-08-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='has_crossfit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='mode',
            field=models.CharField(choices=[('gym', 'Gym'), ('crossfit', 'Crossfit')], default='gym', max_length=10),
        ),
    ]
