# Generated by Django 5.0.1 on 2024-08-09 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_gym_has_crossfit_reservation_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='has_crossfit',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='mode',
        ),
        migrations.AddField(
            model_name='attendance',
            name='gym',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='gym.gym'),
        ),
        migrations.AddField(
            model_name='membership',
            name='gym',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gym.gym'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='gym',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='gym.gym'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gym',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gym.gym'),
        ),
        migrations.AddField(
            model_name='scheduleday',
            name='gym',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_days', to='gym.gym'),
        ),
        migrations.AddField(
            model_name='user',
            name='gym',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_users', to='gym.gym'),
        ),
        migrations.AlterField(
            model_name='scheduleday',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
    ]
