# Generated by Django 5.0.1 on 2024-08-09 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_remove_gym_has_crossfit_remove_reservation_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='gym.gym'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gym.gym'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='gym.gym'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gym.gym'),
        ),
        migrations.AlterField(
            model_name='scheduleday',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_days', to='gym.gym'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gym',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_users', to='gym.gym'),
        ),
    ]
