# Generated by Django 5.0.1 on 2024-01-18 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_remove_penalizacion_motivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10, unique=True)),
                ('closed', models.BooleanField(default=True)),
                ('openTime', models.TimeField(blank=True, null=True)),
                ('closeTime', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidad_horas', models.IntegerField(default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.user')),
            ],
        ),
    ]
