# Generated by Django 5.0.1 on 2024-01-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_horariodia_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariodia',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10, unique=True),
        ),
    ]
