# Generated by Django 5.0.1 on 2024-08-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_alter_attendance_gym_alter_membership_gym_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='scheduleday',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gym',
        ),
        migrations.AddField(
            model_name='gym',
            name='has_crossfit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='mode',
            field=models.CharField(choices=[('gym', 'Gym'), ('crossfit', 'Crossfit')], default='gym', max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduleday',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, unique=True),
        ),
    ]
