# Generated by Django 5.0.1 on 2024-01-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_alter_horariodia_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariodia',
            name='dia',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, unique=True),
        ),
    ]
