# Generated by Django 5.0.1 on 2024-01-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_alter_horariodia_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
