# Generated by Django 5.0.1 on 2024-01-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_reserva_hora_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='gym',
            fields=[
                ('gym_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('aforo_max', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
