# Generated by Django 4.2.6 on 2024-02-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codigo_estudiantil_editado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='programa_editado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono_editado',
            field=models.BooleanField(default=False),
        ),
    ]
